CREATE TABLE empresa (
id BIGINT(20) NOT NULL,
cnpj VARCHAR(255) NOT NULL,
data_atualizacao DATETIME NOT NULL,
data_criacao DATETIME NOT NULL,
razao_social VARCHAR(255) NOT NULL
);

ALTER TABLE empresa
ADD PRIMARY KEY (id);

ALTER TABLE empresa
MODIFY id BIGINT(20) NOT NULL AUTO_INCREMENT;